name: Build C++ STA/LTA Detector

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Python, Python dev headers, and NumPy
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-dev python3-pip
        python3 -m pip install numpy  # <--- Install numpy here EARLY

    - name: Install CMake and g++
      run: |
        sudo apt-get install -y cmake g++

    - name: Configure CMake
      run: |
        rm -rf build   # <-- Clean build folder if it exists
        mkdir build
        cd build
        cmake ..

    - name: Build with Make
      run: |
        cd build
        make
